services:
  simple_api:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/simple_api

  postgres_db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_simple_api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ruslan
      POSTGRES_PASSWORD: ruslan
      POSTGRES_DB: postgres_db

volumes:
  postgres_simple_api: